package com.cisyapp.rest.clasesaux;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.cisyapp.rest.modelo.Usuario;
import com.cisyapp.rest.modelo.Viaje;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Vehiculo generated by hbm2java
 */

public class VehiculoConIgnore implements java.io.Serializable {

	private Integer idvehiculo;
	private Usuario usuario;
	private String matricula;
	private String modelo;
	private String color;
	private String combustible;
	private String marca;
	private String fotovehiculo;
	private Date fechadealta;
	private Set<Viaje> viajes = new HashSet<Viaje>(0);

	public VehiculoConIgnore() {
	}

	public VehiculoConIgnore(Usuario usuario, String matricula, Date fechadealta) {
		this.usuario = usuario;
		this.matricula = matricula;
		this.fechadealta = fechadealta;
	}

	public VehiculoConIgnore(Usuario usuario, String matricula, String modelo, String color, String combustible, String marca,
			String fotovehiculo, Date fechadealta, Set<Viaje> viajes) {
		this.usuario = usuario;
		this.matricula = matricula;
		this.modelo = modelo;
		this.color = color;
		this.combustible = combustible;
		this.marca = marca;
		this.fotovehiculo = fotovehiculo;
		this.fechadealta = fechadealta;
		this.viajes = viajes;
	}

	public Integer getIdvehiculo() {
		return this.idvehiculo;
	}

	public void setIdvehiculo(Integer idvehiculo) {
		this.idvehiculo = idvehiculo;
	}
	
	@JsonIgnore
	public Usuario getUsuario() {
		return this.usuario;	
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getCombustible() {
		return this.combustible;
	}

	public void setCombustible(String combustible) {
		this.combustible = combustible;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getFotovehiculo() {
		return this.fotovehiculo;
	}

	public void setFotovehiculo(String fotovehiculo) {
		this.fotovehiculo = fotovehiculo;
	}

	public Date getFechadealta() {
		return this.fechadealta;
	}

	public void setFechadealta(Date fechadealta) {
		this.fechadealta = fechadealta;
	}

	public Set<Viaje> getViajes() {
		return this.viajes;
	}

	public void setViajes(Set<Viaje> viajes) {
		this.viajes = viajes;
	}

}
