package com.cisyapp.rest.modelo;
// Generated 05-may-2020 17:39:03 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidencia generated by hbm2java
 */
@Entity
@Table(name = "incidencia", catalog = "cisy")
public class Incidencia implements java.io.Serializable {

	private Integer idincidencia;
	private Usuario usuario;
	private String texto;
	private String estado;
	private Date fechacreacion;

	public Incidencia() {
	}

	public Incidencia(Usuario usuario, String texto, Date fechacreacion) {
		this.usuario = usuario;
		this.texto = texto;
		this.fechacreacion = fechacreacion;
	}

	public Incidencia(Usuario usuario, String texto, String estado, Date fechacreacion) {
		this.usuario = usuario;
		this.texto = texto;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idincidencia", unique = true, nullable = false)
	public Integer getIdincidencia() {
		return this.idincidencia;
	}

	public void setIdincidencia(Integer idincidencia) {
		this.idincidencia = idincidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "texto", nullable = false, length = 300)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "estado", length = 9)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreacion", nullable = false, length = 19)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

}
