package com.cisyapp.rest.modelo;
// Generated 05-may-2020 17:39:03 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", catalog = "cisy")
public class Reserva implements java.io.Serializable {

	private ReservaId id;
	private Usuario usuario;
	private Viaje viaje;
	private Date fechareserva;
	private Date horafichaje;

	public Reserva() {
	}

	public Reserva(ReservaId id, Usuario usuario, Viaje viaje, Date fechareserva, Date horafichaje) {
		this.id = id;
		this.usuario = usuario;
		this.viaje = viaje;
		this.fechareserva = fechareserva;
		this.horafichaje = horafichaje;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idreserva", column = @Column(name = "idreserva", nullable = false)),
			@AttributeOverride(name = "idusuariopasajero", column = @Column(name = "idusuariopasajero", nullable = false)),
			@AttributeOverride(name = "idviaje", column = @Column(name = "idviaje", nullable = false)) })
	public ReservaId getId() {
		return this.id;
	}

	public void setId(ReservaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuariopasajero", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idviaje", nullable = false, insertable = false, updatable = false)
	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechareserva", nullable = false, length = 19)
	public Date getFechareserva() {
		return this.fechareserva;
	}

	public void setFechareserva(Date fechareserva) {
		this.fechareserva = fechareserva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horafichaje", nullable = false, length = 19)
	public Date getHorafichaje() {
		return this.horafichaje;
	}

	public void setHorafichaje(Date horafichaje) {
		this.horafichaje = horafichaje;
	}

}
