package com.cisyapp.rest.modelo;
// Generated 05-may-2020 17:39:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservaId generated by hbm2java
 */
@Embeddable
public class ReservaId implements java.io.Serializable {

	private int idreserva;
	private int idusuariopasajero;
	private int idviaje;

	public ReservaId() {
	}

	public ReservaId(int idreserva, int idusuariopasajero, int idviaje) {
		this.idreserva = idreserva;
		this.idusuariopasajero = idusuariopasajero;
		this.idviaje = idviaje;
	}

	@Column(name = "idreserva", nullable = false)
	public int getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(int idreserva) {
		this.idreserva = idreserva;
	}

	@Column(name = "idusuariopasajero", nullable = false)
	public int getIdusuariopasajero() {
		return this.idusuariopasajero;
	}

	public void setIdusuariopasajero(int idusuariopasajero) {
		this.idusuariopasajero = idusuariopasajero;
	}

	@Column(name = "idviaje", nullable = false)
	public int getIdviaje() {
		return this.idviaje;
	}

	public void setIdviaje(int idviaje) {
		this.idviaje = idviaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservaId))
			return false;
		ReservaId castOther = (ReservaId) other;

		return (this.getIdreserva() == castOther.getIdreserva())
				&& (this.getIdusuariopasajero() == castOther.getIdusuariopasajero())
				&& (this.getIdviaje() == castOther.getIdviaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdreserva();
		result = 37 * result + this.getIdusuariopasajero();
		result = 37 * result + this.getIdviaje();
		return result;
	}

}
