package com.cisyapp.rest.modelo;
// Generated 28-may-2020 20:41:23 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Viaje generated by hbm2java
 */
@Entity
@Table(name = "viaje", catalog = "cisy")
public class Viaje implements java.io.Serializable {
	
	
	private Integer idviaje;
	@NotNull
	private Usuario usuario;
	@NotNull
	private Vehiculo vehiculo;
	@NotNull
	@Size(min=1, max=30)
	private String localidadorigen;
	@NotNull
	@Size(min=1, max=30)
	private String lugarsalida;
	private String localidaddestino;
	private String lugarllegada;
	@NotNull
	private BigDecimal precio;
	@NotNull
	private int numplazasdisponibles;
	@NotNull
	private Date fechasalida;
	private Date fechacreacionviaje;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Viaje() {
	}

	public Viaje(Usuario usuario, Vehiculo vehiculo, String localidadorigen, String lugarsalida,
			String localidaddestino, String lugarllegada, int numplazasdisponibles, Date fechacreacionviaje) {
		this.usuario = usuario;
		this.vehiculo = vehiculo;
		this.localidadorigen = localidadorigen;
		this.lugarsalida = lugarsalida;
		this.localidaddestino = localidaddestino;
		this.lugarllegada = lugarllegada;
		this.numplazasdisponibles = numplazasdisponibles;
		this.fechacreacionviaje = fechacreacionviaje;
	}

	public Viaje(Usuario usuario, Vehiculo vehiculo, String localidadorigen, String lugarsalida,
			String localidaddestino, String lugarllegada, BigDecimal precio, int numplazasdisponibles, Date fechasalida,
			Date fechacreacionviaje, Set<Reserva> reservas) {
		this.usuario = usuario;
		this.vehiculo = vehiculo;
		this.localidadorigen = localidadorigen;
		this.lugarsalida = lugarsalida;
		this.localidaddestino = localidaddestino;
		this.lugarllegada = lugarllegada;
		this.precio = precio;
		this.numplazasdisponibles = numplazasdisponibles;
		this.fechasalida = fechasalida;
		this.fechacreacionviaje = fechacreacionviaje;
		this.reservas = reservas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idviaje", unique = true, nullable = false)
	public Integer getIdviaje() {
		return this.idviaje;
	}

	public void setIdviaje(Integer idviaje) {
		this.idviaje = idviaje;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idusuarioconductor", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idvehiculo", nullable = false)
	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Column(name = "localidadorigen", nullable = false, length = 30)
	public String getLocalidadOrigen() {
		return this.localidadorigen;
	}

	public void setLocalidadOrigen(String localidadorigen) {
		this.localidadorigen = localidadorigen;
	}

	@Column(name = "lugarsalida", nullable = false, length = 30)
	public String getLugarSalida() {
		return this.lugarsalida;
	}

	public void setLugarSalida(String lugarsalida) {
		this.lugarsalida = lugarsalida;
	}

	@Column(name = "localidaddestino", nullable = false, length = 30)
	public String getLocalidadDestino() {
		return this.localidaddestino;
	}

	public void setLocalidadDestino(String localidaddestino) {
		this.localidaddestino = localidaddestino;
	}

	@Column(name = "lugarllegada", nullable = false, length = 30)
	public String getLugarLlegada() {
		return this.lugarllegada;
	}

	public void setLugarLlegada(String lugarllegada) {
		this.lugarllegada = lugarllegada;
	}

	@Column(name = "precio", precision = 4)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "numplazasdisponibles", nullable = false)
	public int getNumplazasdisponibles() {
		return this.numplazasdisponibles;
	}

	public void setNumplazasdisponibles(int numplazasdisponibles) {
		this.numplazasdisponibles = numplazasdisponibles;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechasalida", length = 19)
	public Date getFechasalida() {
		return this.fechasalida;
	}

	public void setFechasalida(Date fechasalida) {
		this.fechasalida = fechasalida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreacionviaje", nullable = false, length = 19)
	public Date getFechacreacionviaje() {
		return this.fechacreacionviaje;
	}

	public void setFechacreacionviaje(Date fechacreacionviaje) {
		this.fechacreacionviaje = fechacreacionviaje;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "viaje")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
